In [3]:
import pandas as pd

In [4]:
df = pd.read_parquet('../data/processed/nvd_dataset.parquet')

In [38]:
df.head(5)

,CVE_ID,PUBLISHED_DATE,MODIFIED_DATE,CVE_YEAR,HAS_KEV,DESC_EN,SCORE_BASE,SEVERITY,VEC_ATAQUE,COMPLEJIDAD,...,INTERACCION,ALCANCE,IMP_CONFID,IMP_INTEGR,IMP_DISPON,FACILIDAD,CWE_ID,CPE_VENDOR,CPE_PRODUCT,PATCH_URL
0,CVE-2026-7653,2026-05-02 16:16:16.033000+00:00,2026-05-02 16:16:16.033000+00:00,2026,False,A security flaw has been discovered in r-huijt...,6.3,MEDIUM,NETWORK,LOW,...,NONE,UNCHANGED,LOW,LOW,LOW,2.8,CWE-77,NaN,NaN,https://github.com/r-huijts/rijksmuseum-mcp/is...
1,CVE-2026-7645,2026-05-02 16:16:15.867000+00:00,2026-05-02 16:16:15.867000+00:00,2026,False,A vulnerability was found in ruvnet sublinear-...,6.5,MEDIUM,NETWORK,LOW,...,NONE,UNCHANGED,NONE,LOW,LOW,3.9,CWE-22,NaN,NaN,https://github.com/ruvnet/sublinear-time-solver/
2,CVE-2026-7644,2026-05-02 15:16:14.373000+00:00,2026-05-02 15:16:14.373000+00:00,2026,False,A vulnerability has been found in ChatGPTNextW...,7.3,HIGH,NETWORK,LOW,...,NONE,UNCHANGED,LOW,LOW,LOW,3.9,CWE-266,NaN,NaN,https://github.com/ChatGPTNextWeb/NextChat/
3,CVE-2026-7643,2026-05-02 15:16:14.203000+00:00,2026-05-02 15:16:14.203000+00:00,2026,False,A flaw has been found in ChatGPTNextWeb NextCh...,4.3,MEDIUM,NETWORK,LOW,...,REQUIRED,UNCHANGED,NONE,LOW,NONE,2.8,CWE-346,NaN,NaN,https://github.com/ChatGPTNextWeb/NextChat/
4,CVE-2026-7642,2026-05-02 15:16:14.047000+00:00,2026-05-02 15:16:14.047000+00:00,2026,False,A vulnerability was detected in pskill9 websit...,6.3,MEDIUM,NETWORK,LOW,...,NONE,UNCHANGED,LOW,LOW,LOW,2.8,CWE-77,NaN,NaN,https://github.com/BruceJqs/public_exp/issues/31

# Analisis Exploratorio

In [31]:
print(f"Tamaño del dataset\nFilas: {len(df):,} | Columnas: {len(df.columns)}")

Tamaño del dataset
Filas: 347,752 | Columnas: 21

In [37]:
df.sample(5)

,CVE_ID,PUBLISHED_DATE,MODIFIED_DATE,CVE_YEAR,HAS_KEV,DESC_EN,SCORE_BASE,SEVERITY,VEC_ATAQUE,COMPLEJIDAD,...,INTERACCION,ALCANCE,IMP_CONFID,IMP_INTEGR,IMP_DISPON,FACILIDAD,CWE_ID,CPE_VENDOR,CPE_PRODUCT,PATCH_URL
78587,CVE-2024-47905,2024-11-12 16:15:22.473000+00:00,2024-11-18 15:08:47.280000+00:00,2024,False,A stack-based buffer overflow in Ivanti Connec...,4.9,MEDIUM,NETWORK,LOW,...,NONE,UNCHANGED,NONE,NONE,HIGH,1.2,CWE-121,ivanti,connect_secure,https://forums.ivanti.com/s/article/Security-A...
137777,CVE-2023-1152,2023-03-17 09:15:12.533000+00:00,2025-02-26 17:15:14.377000+00:00,2023,False,Improper Neutralization of Special Elements us...,9.8,CRITICAL,NETWORK,LOW,...,NONE,UNCHANGED,HIGH,HIGH,HIGH,3.9,CWE-89,utarit,persolus,https://www.usom.gov.tr/bildirim/tr-23-0154-2
34086,CVE-2025-58288,2025-10-11 09:15:33.487000+00:00,2025-10-16 15:23:55.150000+00:00,2025,False,Denial of service (DoS) vulnerability in the o...,5.5,MEDIUM,LOCAL,LOW,...,REQUIRED,UNCHANGED,NONE,NONE,HIGH,1.8,CWE-275,huawei,harmonyos,https://consumer.huawei.com/en/support/bulleti...
226070,CVE-2019-9490,2019-04-05 23:29:00.267000+00:00,2024-11-21 04:51:43.193000+00:00,2019,False,A vulnerability in Trend Micro InterScan Web S...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,trendmicro,interscan_web_security_virtual_appliance,http://www.securityfocus.com/bid/107848
163427,CVE-2022-28662,2022-04-12 09:15:15.327000+00:00,2024-11-21 06:57:40.730000+00:00,2022,False,A vulnerability has been identified in Simcent...,6.5,MEDIUM,NETWORK,LOW,...,REQUIRED,UNCHANGED,HIGH,NONE,NONE,2.8,CWE-787,siemens,simcenter_femap,https://cert-portal.siemens.com/productcert/pd...

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 347752 entries, 0 to 347751
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   CVE_ID          347752 non-null  str
 1   PUBLISHED_DATE  347752 non-null  datetime64[us, UTC]
 2   MODIFIED_DATE   347752 non-null  datetime64[us, UTC]
 3   CVE_YEAR        347752 non-null  Int64
 4   HAS_KEV         347752 non-null  bool
 5   DESC_EN         347752 non-null  str
 6   SCORE_BASE      209991 non-null  float64
 7   SEVERITY        209991 non-null  str
 8   VEC_ATAQUE      209991 non-null  str
 9   COMPLEJIDAD     209991 non-null  str
 10  PRIVILEGIOS     209991 non-null  str
 11  INTERACCION     209991 non-null  str
 12  ALCANCE         209991 non-null  str
 13  IMP_CONFID      209991 non-null  str
 14  IMP_INTEGR      209991 non-null  str
 15  IMP_DISPON      209991 non-null  str
 16  FACILIDAD       209991 non-null  float64
 17  CWE_ID          274234 non-null  str
 18  CPE_VENDOR      296193 non-null  str
 19  CPE_PRODUCT     296192 non-null  str
 20  PATCH_URL       330227 non-null  str
dtypes: Int64(1), bool(1), datetime64[us, UTC](2), float64(2), str(15)
memory usage: 206.0 MB

In [42]:
df.columns

Index(['CVE_ID', 'PUBLISHED_DATE', 'MODIFIED_DATE', 'CVE_YEAR', 'HAS_KEV',
       'DESC_EN', 'SCORE_BASE', 'SEVERITY', 'VEC_ATAQUE', 'COMPLEJIDAD',
       'PRIVILEGIOS', 'INTERACCION', 'ALCANCE', 'IMP_CONFID', 'IMP_INTEGR',
       'IMP_DISPON', 'FACILIDAD', 'CWE_ID', 'CPE_VENDOR', 'CPE_PRODUCT',
       'PATCH_URL'],
      dtype='str')

In [34]:
df.dtypes

CVE_ID                            str
PUBLISHED_DATE    datetime64[us, UTC]
MODIFIED_DATE     datetime64[us, UTC]
CVE_YEAR                        Int64
HAS_KEV                          bool
DESC_EN                           str
SCORE_BASE                    float64
SEVERITY                          str
VEC_ATAQUE                        str
COMPLEJIDAD                       str
PRIVILEGIOS                       str
INTERACCION                       str
ALCANCE                           str
IMP_CONFID                        str
IMP_INTEGR                        str
IMP_DISPON                        str
FACILIDAD                     float64
CWE_ID                            str
CPE_VENDOR                        str
CPE_PRODUCT                       str
PATCH_URL                         str
dtype: object

In [35]:
df.describe()

         CVE_YEAR     SCORE_BASE      FACILIDAD
count    347752.0  209991.000000  209991.000000
mean   2018.87837       6.836727       2.598704
std      6.295192       1.718558       0.947715
min        1999.0       0.000000       0.100000
25%        2016.0       5.500000       1.800000
50%        2021.0       6.700000       2.800000
75%        2024.0       7.800000       3.900000
max        2026.0      10.000000       3.900000

# Analisis de Limpieza

In [39]:
df.isnull().sum()

CVE_ID                 0
PUBLISHED_DATE         0
MODIFIED_DATE          0
CVE_YEAR               0
HAS_KEV                0
DESC_EN                0
SCORE_BASE        137761
SEVERITY          137761
VEC_ATAQUE        137761
COMPLEJIDAD       137761
PRIVILEGIOS       137761
INTERACCION       137761
ALCANCE           137761
IMP_CONFID        137761
IMP_INTEGR        137761
IMP_DISPON        137761
FACILIDAD         137761
CWE_ID             73518
CPE_VENDOR         51559
CPE_PRODUCT        51560
PATCH_URL          17525
dtype: int64

In [41]:
df.nunique()

CVE_ID            347752
PUBLISHED_DATE    318911
MODIFIED_DATE     224262
CVE_YEAR              28
HAS_KEV                2
DESC_EN           318406
SCORE_BASE            84
SEVERITY               5
VEC_ATAQUE             4
COMPLEJIDAD            2
PRIVILEGIOS            3
INTERACCION            2
ALCANCE                2
IMP_CONFID             3
IMP_INTEGR             3
IMP_DISPON             3
FACILIDAD             26
CWE_ID               752
CPE_VENDOR         35530
CPE_PRODUCT        59636
PATCH_URL         235526
dtype: int64

In [8]:
df['CPE_VENDOR'].value_counts()

CPE_VENDOR
microsoft             13872
linux                 12547
google                12351
oracle                 8724
apple                  8153
                      ...
john_s._roberts           1
satan                     1
ncsa_httpd_project        1
rpc.walld                 1
commodore                 1
Name: count, Length: 35530, dtype: int64

In [10]:
df['CPE_PRODUCT'].value_counts()

CPE_PRODUCT
linux_kernel       12510
android             8266
chrome              3765
windows_10          2876
firefox             2686
                   ...
rpc.walld              1
dec_openvms_axp        1
amiga_unix             1
vms                    1
nex                    1
Name: count, Length: 59636, dtype: int64

In [13]:
df['CPE_VENDOR'].value_counts().reset_index().rename(
    columns={'index':'vendor','CPE_VENDOR':'total_cves'}
).to_csv('../data/processed/vendors_unicos.csv', index=False)

In [14]:
df['CPE_PRODUCT'].value_counts().reset_index().rename(
    columns={'index':'product','CPE_PRODUCT':'total_cves'}
).to_csv('../data/processed/products_unicos.csv', index=False)

In [43]:
df['CWE_ID'].value_counts().reset_index().rename(
    columns={'index':'cwe','CWE_ID':'total_cves'}
).to_csv('../data/processed/cwe_unicos.csv', index=False)

In [45]:
con_cpe = df[df['CPE_VENDOR'].notna()]
con_cvss = con_cpe[con_cpe['SCORE_BASE'].notna()]
sin_cvss = con_cpe[con_cpe['SCORE_BASE'].isna()]

print(f'Con CPE + CVSS v3.1: {len(con_cvss):,}')
print(f'Con CPE sin CVSS v3.1: {len(sin_cvss):,}')
print(f'HAS_KEV activos: {con_cvss["HAS_KEV"].sum():,}')

Con CPE + CVSS v3.1: 181,279
Con CPE sin CVSS v3.1: 114,914
HAS_KEV activos: 1,582

# Limpieza para el modelo

In [44]:
df_modelo = df[
    df['CPE_VENDOR'].notna() & 
    df['SCORE_BASE'].notna()
].copy()

print(f"Dataset modelo: {len(df_modelo):,} CVEs")

Dataset modelo: 181,279 CVEs

In [46]:
df_modelo.isnull().sum()

CVE_ID                0
PUBLISHED_DATE        0
MODIFIED_DATE         0
CVE_YEAR              0
HAS_KEV               0
DESC_EN               0
SCORE_BASE            0
SEVERITY              0
VEC_ATAQUE            0
COMPLEJIDAD           0
PRIVILEGIOS           0
INTERACCION           0
ALCANCE               0
IMP_CONFID            0
IMP_INTEGR            0
IMP_DISPON            0
FACILIDAD             0
CWE_ID            17715
CPE_VENDOR            0
CPE_PRODUCT           2
PATCH_URL             0
dtype: int64

In [47]:
df_modelo['SEVERITY'].value_counts()

SEVERITY
MEDIUM      83741
HIGH        68689
CRITICAL    21664
LOW          7155
NONE           30
Name: count, dtype: int64

In [48]:
df_modelo['CPE_VENDOR'].value_counts().head(20)

CPE_VENDOR
linux        10761
google        8486
microsoft     7669
adobe         4038
ibm           3683
apple         3676
oracle        3470
cisco         2822
qualcomm      1848
tenda         1813
huawei        1668
apache        1624
dlink         1525
siemens       1486
jenkins       1432
intel         1399
mozilla       1385
dell          1325
samsung       1309
gitlab        1228
Name: count, dtype: int64