In [189]:
import pandas as pd
import numpy as np

In [190]:
df_Oscar = pd.read_parquet('../data/processed/nvd_dataset.parquet')
df_Camilo = pd.read_parquet('../data/processed/df_Nuevo.parquet')

In [191]:
diferencias = df_Oscar.equals(df_Camilo)

In [192]:
print(df_Camilo.columns)
print(df_Oscar.columns)

Index(['CVE_ID', 'IS_KEV', 'RISK_TIER', 'RISK_SCORE', 'EPSS_SCORE',
       'EPSS_PERCENTILE', 'SCORE_BASE', 'SEVERITY', 'VEC_ATAQUE',
       'COMPLEJIDAD', 'PRIVILEGIOS', 'INTERACCION', 'DAYS_SINCE_PUBLISHED',
       'VENDOR', 'PRODUCT', 'CWE', 'VENDOR_TOKENS', 'PRODUCT_TOKENS',
       'CWE_TOKENS', 'VENDOR_GROUPS_STR', 'PRODUCT_GROUPS_STR',
       'CWE_TECH_GROUPS_STR', 'CWE_CANONICAL_STR', 'N_VENDOR_GROUPS',
       'N_PRODUCT_GROUPS', 'N_CWE_GROUPS'],
      dtype='str')
Index(['CVE_ID', 'PUBLISHED_DATE', 'MODIFIED_DATE', 'CVE_YEAR', 'HAS_KEV',
       'DESC_EN', 'SCORE_BASE', 'SEVERITY', 'VEC_ATAQUE', 'COMPLEJIDAD',
       'PRIVILEGIOS', 'INTERACCION', 'ALCANCE', 'IMP_CONFID', 'IMP_INTEGR',
       'IMP_DISPON', 'FACILIDAD', 'CWE_ID', 'CPE_VENDOR', 'CPE_PRODUCT',
       'PATCH_URL'],
      dtype='str')

In [193]:
resultado = pd.merge(df_Oscar, df_Camilo, how="outer", on="CVE_ID")
print(resultado)

               CVE_ID            PUBLISHED_DATE  \
0       CVE-1999-0001 1999-12-30 05:00:00+00:00
1       CVE-1999-0002 1998-10-12 04:00:00+00:00
2       CVE-1999-0003 1998-04-01 05:00:00+00:00
3       CVE-1999-0004 1997-12-16 05:00:00+00:00
4       CVE-1999-0005 1998-07-20 04:00:00+00:00
...               ...                       ...
347762  CVE-2026-7677                       NaT
347763  CVE-2026-7678                       NaT
347764  CVE-2026-7679                       NaT
347765  CVE-2026-7680                       NaT
347766  CVE-2026-7681                       NaT

                          MODIFIED_DATE  CVE_YEAR HAS_KEV  \
0      2026-04-16 00:27:16.627000+00:00      1999   False
1      2026-04-16 00:27:16.627000+00:00      1999   False
2      2026-04-16 00:27:16.627000+00:00      1999   False
3      2026-04-16 00:27:16.627000+00:00      1999   False
4      2026-04-16 00:27:16.627000+00:00      1999   False
...                                 ...       ...     ...
347762                              NaT      <NA>     NaN
347763                              NaT      <NA>     NaN
347764                              NaT      <NA>     NaN
347765                              NaT      <NA>     NaN
347766                              NaT      <NA>     NaN

                                                  DESC_EN  SCORE_BASE_x  \
0       ip_input.c in BSD-derived TCP/IP implementatio...           NaN
1       Buffer overflow in NFS mountd gives root acces...           NaN
2       Execute commands as root via buffer overflow i...           NaN
3       MIME buffer overflow in email clients, e.g. So...           NaN
4       Arbitrary command execution via IMAP buffer ov...           NaN
...                                                   ...           ...
347762                                                NaN           NaN
347763                                                NaN           NaN
347764                                                NaN           NaN
347765                                                NaN           NaN
347766                                                NaN           NaN

       SEVERITY_x VEC_ATAQUE_x COMPLEJIDAD_x  ...  \
0             NaN          NaN           NaN  ...
1             NaN          NaN           NaN  ...
2             NaN          NaN           NaN  ...
3             NaN          NaN           NaN  ...
4             NaN          NaN           NaN  ...
...           ...          ...           ...  ...
347762        NaN          NaN           NaN  ...
347763        NaN          NaN           NaN  ...
347764        NaN          NaN           NaN  ...
347765        NaN          NaN           NaN  ...
347766        NaN          NaN           NaN  ...

                               VENDOR_TOKENS  \
0                   [freebsd, bsdi, openbsd]
1                    [bsdi, redhat, caldera]
2              [sun, ibm, tritreal, sgi, hp]
3        [hp, university_of_washington, sco]
4       [netscape, university_of_washington]
...                                      ...
347762                             [UNKNOWN]
347763                             [UNKNOWN]
347764                             [UNKNOWN]
347765                             [UNKNOWN]
347766                             [UNKNOWN]

                                     PRODUCT_TOKENS          CWE_TOKENS  \
0                        [freebsd, bsd_os, openbsd]            [cwe-20]
1                        [linux, bsd_os, openlinux]           [cwe-119]
2       [sunos, aix, irix, hp-ux, solaris, ted_cde]     [nvd-cwe-other]
3                          [pine, dtmail, unixware]     [nvd-cwe-other]
4                          [messaging_server, imap]     [nvd-cwe-other]
...                                             ...                 ...
347762                                    [UNKNOWN]    [cwe-79, cwe-94]
347763                                    [UNKNOWN]    [cwe-74, cwe-89]
347764                                    [UNKNOWN]           [cwe-287]
347765                                    [UNKNOWN]            [cwe-22]
347766                                    [UNKNOWN]  [cwe-285, cwe-639]

                    VENDOR_GROUPS_STR                PRODUCT_GROUPS_STR  \
0                        OTHER_VENDOR                    other_software
1               OTHER_VENDOR | redhat  linux_ecosystem | other_software
2       sun | ibm | OTHER_VENDOR | hp   other_software | enterprise_app
3                   hp | OTHER_VENDOR                    other_software
4                        OTHER_VENDOR                    other_software
...                               ...                               ...
347762                        unknown                    other_software
347763                        unknown                    other_software
347764                        unknown                    other_software
347765                        unknown                    other_software
347766                        unknown                    other_software

                   CWE_TECH_GROUPS_STR  CWE_CANONICAL_STR N_VENDOR_GROUPS  \
0                     input_validation             cwe-20             1.0
1                    memory_corruption            cwe-787             2.0
2                                other      nvd-cwe-other             4.0
3                                other      nvd-cwe-other             2.0
4                                other      nvd-cwe-other             1.0
...                                ...                ...             ...
347762  xss_injection | code_injection    cwe-79 | cwe-94             1.0
347763  injection | database_injection    cwe-74 | cwe-89             1.0
347764                  authentication            cwe-287             1.0
347765                  path_traversal             cwe-22             1.0
347766                           other  cwe-285 | cwe-639             1.0

       N_PRODUCT_GROUPS N_CWE_GROUPS
0                   1.0          1.0
1                   2.0          1.0
2                   2.0          1.0
3                   1.0          1.0
4                   1.0          1.0
...                 ...          ...
347762              1.0          2.0
347763              1.0          2.0
347764              1.0          1.0
347765              1.0          1.0
347766              1.0          1.0

[347767 rows x 46 columns]

In [145]:
resultado.head()

,CVE_ID,PUBLISHED_DATE,MODIFIED_DATE,CVE_YEAR,HAS_KEV,DESC_EN,SCORE_BASE_x,SEVERITY_x,VEC_ATAQUE_x,COMPLEJIDAD_x,...,VENDOR_TOKENS,PRODUCT_TOKENS,CWE_TOKENS,VENDOR_GROUPS_STR,PRODUCT_GROUPS_STR,CWE_TECH_GROUPS_STR,CWE_CANONICAL_STR,N_VENDOR_GROUPS,N_PRODUCT_GROUPS,N_CWE_GROUPS
0,CVE-1999-0001,1999-12-30 05:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,False,ip_input.c in BSD-derived TCP/IP implementatio...,NaN,NaN,NaN,NaN,...,"[freebsd, bsdi, openbsd]","[freebsd, bsd_os, openbsd]",[cwe-20],OTHER_VENDOR,other_software,input_validation,cwe-20,1.0,1.0,1.0
1,CVE-1999-0002,1998-10-12 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,False,Buffer overflow in NFS mountd gives root acces...,NaN,NaN,NaN,NaN,...,"[bsdi, redhat, caldera]","[linux, bsd_os, openlinux]",[cwe-119],OTHER_VENDOR | redhat,linux_ecosystem | other_software,memory_corruption,cwe-787,2.0,2.0,1.0
2,CVE-1999-0003,1998-04-01 05:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,False,Execute commands as root via buffer overflow i...,NaN,NaN,NaN,NaN,...,"[sun, ibm, tritreal, sgi, hp]","[sunos, aix, irix, hp-ux, solaris, ted_cde]",[nvd-cwe-other],sun | ibm | OTHER_VENDOR | hp,other_software | enterprise_app,other,nvd-cwe-other,4.0,2.0,1.0
3,CVE-1999-0004,1997-12-16 05:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,False,"MIME buffer overflow in email clients, e.g. So...",NaN,NaN,NaN,NaN,...,"[hp, university_of_washington, sco]","[pine, dtmail, unixware]",[nvd-cwe-other],hp | OTHER_VENDOR,other_software,other,nvd-cwe-other,2.0,1.0,1.0
4,CVE-1999-0005,1998-07-20 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,False,Arbitrary command execution via IMAP buffer ov...,NaN,NaN,NaN,NaN,...,"[netscape, university_of_washington]","[messaging_server, imap]",[nvd-cwe-other],OTHER_VENDOR,other_software,other,nvd-cwe-other,1.0,1.0,1.0

In [194]:
resultado.columns

Index(['CVE_ID', 'PUBLISHED_DATE', 'MODIFIED_DATE', 'CVE_YEAR', 'HAS_KEV',
       'DESC_EN', 'SCORE_BASE_x', 'SEVERITY_x', 'VEC_ATAQUE_x',
       'COMPLEJIDAD_x', 'PRIVILEGIOS_x', 'INTERACCION_x', 'ALCANCE',
       'IMP_CONFID', 'IMP_INTEGR', 'IMP_DISPON', 'FACILIDAD', 'CWE_ID',
       'CPE_VENDOR', 'CPE_PRODUCT', 'PATCH_URL', 'IS_KEV', 'RISK_TIER',
       'RISK_SCORE', 'EPSS_SCORE', 'EPSS_PERCENTILE', 'SCORE_BASE_y',
       'SEVERITY_y', 'VEC_ATAQUE_y', 'COMPLEJIDAD_y', 'PRIVILEGIOS_y',
       'INTERACCION_y', 'DAYS_SINCE_PUBLISHED', 'VENDOR', 'PRODUCT', 'CWE',
       'VENDOR_TOKENS', 'PRODUCT_TOKENS', 'CWE_TOKENS', 'VENDOR_GROUPS_STR',
       'PRODUCT_GROUPS_STR', 'CWE_TECH_GROUPS_STR', 'CWE_CANONICAL_STR',
       'N_VENDOR_GROUPS', 'N_PRODUCT_GROUPS', 'N_CWE_GROUPS'],
      dtype='str')

In [195]:
resultado.shape

(347767, 46)

#### Unificaicon Severity

In [196]:
print(resultado["SEVERITY_x"].value_counts())
print(resultado["SEVERITY_y"].value_counts())

SEVERITY_x
MEDIUM      98730
HIGH        78729
CRITICAL    24344
LOW          8155
NONE           33
Name: count, dtype: int64
SEVERITY_y
MEDIUM      115400
HIGH         97996
UNKNOWN      72445
CRITICAL     30634
LOW           9010
Name: count, dtype: int64

In [202]:
resultado['SEVERITY'] = np.where(
    resultado['SEVERITY_y'].isna() | (resultado['SEVERITY_y'] == 'UNKNOWN'), 
    resultado['SEVERITY_x'], 
    resultado['SEVERITY_y']
)

In [203]:
resultado["SEVERITY"].unique()

<ArrowStringArray>
[nan, 'CRITICAL', 'MEDIUM', 'HIGH', 'LOW', 'NONE']
Length: 6, dtype: str

In [204]:
resultado["SEVERITY"] = resultado["SEVERITY"].replace("UNKNOWN", np.nan)

In [205]:
resultado["SEVERITY"].value_counts()

SEVERITY
MEDIUM      115400
HIGH         97996
CRITICAL     30634
LOW           9010
NONE            33
Name: count, dtype: int64

In [206]:
resultado = resultado.drop(["SEVERITY_x", "SEVERITY_y"], axis=1)

In [207]:
resultado.shape

(347767, 45)

#### Unificaicon SCORE_BASE

In [208]:
print(resultado["SCORE_BASE_x"].value_counts())
print(resultado["SCORE_BASE_y"].value_counts())

SCORE_BASE_x
7.5    18364
9.8    17975
7.8    16777
5.5    15477
8.8    15055
       ...
1.8       24
2.1       15
1.6        8
9.2        6
1.7        2
Name: count, Length: 84, dtype: int64
SCORE_BASE_y
7.5    37618
7.8    23744
9.8    23600
4.3    20497
8.8    19728
       ...
1.0        8
9.2        6
9.7        4
1.3        2
1.4        2
Name: count, Length: 89, dtype: int64

In [209]:
print(resultado["SCORE_BASE_x"].unique())
print(resultado["SCORE_BASE_y"].unique())

[ nan  9.8  5.4  7.   8.4  7.8  7.3  7.5  3.5  8.2  5.5  7.1  8.8  5.3
  9.1  3.3  6.1  6.5  5.6  3.7  5.   5.9  4.8  4.7  4.5  4.3  8.1  6.3
  7.2  6.8  4.6  4.4  6.7  3.1  9.9  5.8  8.   2.6 10.   7.4  7.7  2.4
  6.   8.6  9.6  5.7  4.9  6.4  8.3  2.7  9.   6.2  9.3  3.8  4.   3.4
  4.2  6.6  3.9  2.8  5.1  7.6  7.9  4.1  2.   2.5  8.5  1.9  8.9  8.7
  3.6  2.3  3.   9.4  2.2  6.9  5.2  1.6  1.8  2.9  2.1  3.2  1.7  0.
  9.2]
[ 5.  10.   9.8  5.4  7.   8.4  7.2  7.5  nan  7.8  4.6  2.6  7.3  5.1
  6.4  1.9  2.1  3.7  7.6  3.5  6.2  6.8  9.3  1.2  8.2  4.9  4.   3.6
  7.1  5.5  4.3  9.   3.3  8.8  5.3  1.7  6.9  6.5  5.8  9.1  3.8  8.5
  8.3  6.6  9.4  4.4  6.   6.1  5.2  4.8  6.3  5.6  4.7  5.9  1.   4.5
  8.1  5.7  1.5  3.2  9.7  2.3  4.1  2.4  2.7  2.9  7.9  3.4  7.4  1.8
  4.2  6.7  3.   3.1  9.9  8.   7.7  1.3  8.6  2.8  9.6  2.   1.4  3.9
  8.7  2.5  1.6  2.2  8.9  9.2]

In [211]:
resultado['SCORE_BASE'] = np.where(
    resultado['SCORE_BASE_x'].isna() | (resultado['SCORE_BASE_y'].isna()), 
    resultado['SCORE_BASE_y'], 
    resultado['SCORE_BASE_x']
)

In [212]:
resultado["SCORE_BASE"].unique()

array([ 5. , 10. ,  9.8,  5.4,  7. ,  8.4,  7.2,  7.5,  nan,  7.8,  4.6,
        2.6,  7.3,  5.1,  6.4,  1.9,  2.1,  3.7,  7.6,  3.5,  6.2,  6.8,
        9.3,  1.2,  8.2,  4.9,  4. ,  3.6,  7.1,  5.5,  4.3,  9. ,  3.3,
        8.8,  5.3,  1.7,  6.9,  6.5,  5.8,  9.1,  3.8,  8.5,  8.3,  6.6,
        9.4,  4.4,  6. ,  6.1,  5.2,  4.8,  6.3,  5.6,  4.7,  5.9,  1. ,
        4.5,  8.1,  5.7,  1.5,  3.2,  9.7,  2.3,  4.1,  2.4,  2.7,  2.9,
        7.9,  3.4,  7.4,  1.8,  4.2,  6.7,  3. ,  3.1,  9.9,  8. ,  7.7,
        1.3,  8.6,  2.8,  9.6,  2. ,  1.4,  3.9,  8.7,  2.5,  1.6,  2.2,
        8.9,  9.2])

In [213]:
print(resultado["SCORE_BASE"].value_counts())

SCORE_BASE
7.5    37618
7.8    23744
9.8    23600
4.3    20497
8.8    19728
       ...
1.0        8
9.2        6
9.7        4
1.3        2
1.4        2
Name: count, Length: 89, dtype: int64

In [214]:
resultado = resultado.drop(["SCORE_BASE_x", "SCORE_BASE_y"], axis=1)

#### Unificaicon INTERACCION

In [215]:
print(resultado["INTERACCION_x"].value_counts())
print(resultado["INTERACCION_y"].value_counts())

INTERACCION_x
NONE        144792
REQUIRED     65199
Name: count, dtype: int64
INTERACCION_y
NONE        170269
REQUIRED     82771
UNKNOWN      72445
Name: count, dtype: int64

In [216]:
resultado['INTERACCION'] = np.where(
    resultado['INTERACCION_y'].isna() | (resultado['INTERACCION_y'] == 'Unknown'), 
    resultado['INTERACCION_x'], 
    resultado['INTERACCION_y']
)

In [217]:
print(resultado["INTERACCION"].value_counts())

INTERACCION
NONE        170294
REQUIRED     82779
UNKNOWN      72445
Name: count, dtype: int64

In [220]:
resultado["INTERACCION"] = resultado["INTERACCION"].replace("UNKNOWN", np.nan)
resultado["INTERACCION"].unique()

<ArrowStringArray>
[nan, 'NONE', 'REQUIRED']
Length: 3, dtype: str

In [221]:
resultado = resultado.drop(["INTERACCION_x", "INTERACCION_y"], axis=1)

#### Unificaicon PRIVILEGIOS

In [223]:
print(resultado["PRIVILEGIOS_x"].value_counts())
print(resultado["PRIVILEGIOS_y"].value_counts())

PRIVILEGIOS_x
NONE    110905
LOW      77811
HIGH     21275
Name: count, dtype: int64
PRIVILEGIOS_y
NONE       141446
LOW         88275
UNKNOWN     72445
HIGH        23319
Name: count, dtype: int64

In [224]:
resultado['PRIVILEGIOS'] = np.where(
    resultado['PRIVILEGIOS_y'].isna() | (resultado['PRIVILEGIOS_y'] == 'Unknown'), 
    resultado['PRIVILEGIOS_x'], 
    resultado['PRIVILEGIOS_y']
)

In [226]:
resultado["PRIVILEGIOS"] = resultado["PRIVILEGIOS"].replace("UNKNOWN", np.nan)
print(resultado["PRIVILEGIOS"].value_counts())
print()
print(resultado["PRIVILEGIOS"].unique())

PRIVILEGIOS
NONE    141470
LOW      88281
HIGH     23322
Name: count, dtype: int64

<ArrowStringArray>
[nan, 'NONE', 'LOW', 'HIGH']
Length: 4, dtype: str

In [170]:
resultado = resultado.drop(["PRIVILEGIOS_y", "PRIVILEGIOS_x"], axis=1)

#### Unificaicon VEC Ataque

In [227]:
print(resultado["VEC_ATAQUE_x"].value_counts())
print(resultado["VEC_ATAQUE_y"].value_counts())

VEC_ATAQUE_x
NETWORK             151782
LOCAL                50039
ADJACENT_NETWORK      6156
PHYSICAL              2014
Name: count, dtype: int64
VEC_ATAQUE_y
NETWORK             183259
UNKNOWN              72445
LOCAL                60415
ADJACENT_NETWORK      6930
PHYSICAL              2436
Name: count, dtype: int64

In [228]:
resultado['VEC_ATAQUE'] = np.where(
    resultado['VEC_ATAQUE_y'].isna() | (resultado['VEC_ATAQUE_y'] == 'Unknown'), 
    resultado['VEC_ATAQUE_x'], 
    resultado['VEC_ATAQUE_y']
)

In [230]:
resultado["VEC_ATAQUE"] = resultado["VEC_ATAQUE"].replace("UNKNOWN", np.nan)
print(resultado["VEC_ATAQUE"].value_counts())
print()
print(resultado["VEC_ATAQUE"].unique())

VEC_ATAQUE
NETWORK             183286
LOCAL                60420
ADJACENT_NETWORK      6930
PHYSICAL              2437
Name: count, dtype: int64

<ArrowStringArray>
[nan, 'NETWORK', 'ADJACENT_NETWORK', 'LOCAL', 'PHYSICAL']
Length: 5, dtype: str

In [231]:
resultado = resultado.drop(["VEC_ATAQUE_y", "VEC_ATAQUE_x"], axis=1)

#### Unifivacion PRIVILEGIOS

In [234]:
print(resultado["PRIVILEGIOS_x"].value_counts())
print(resultado["PRIVILEGIOS_y"].value_counts())

PRIVILEGIOS_x
NONE    110905
LOW      77811
HIGH     21275
Name: count, dtype: int64
PRIVILEGIOS_y
NONE       141446
LOW         88275
UNKNOWN     72445
HIGH        23319
Name: count, dtype: int64

In [235]:
resultado['PRIVILEGIOS'] = np.where(
    resultado['PRIVILEGIOS_y'].isna() | (resultado['PRIVILEGIOS_y'] == 'Unknown'), 
    resultado['PRIVILEGIOS_x'], 
    resultado['PRIVILEGIOS_y']
)

In [237]:
resultado["PRIVILEGIOS"] = resultado["PRIVILEGIOS"].replace("UNKNOWN", np.nan)
print(resultado["PRIVILEGIOS"].value_counts())
print()
print(resultado["PRIVILEGIOS"].unique())

PRIVILEGIOS
NONE    141470
LOW      88281
HIGH     23322
Name: count, dtype: int64

<ArrowStringArray>
[nan, 'NONE', 'LOW', 'HIGH']
Length: 4, dtype: str

In [238]:
resultado = resultado.drop(["PRIVILEGIOS_y", "PRIVILEGIOS_x"], axis=1)

#### Unificaicon Complejidad

In [244]:
print(resultado["COMPLEJIDAD_x"].value_counts())
print(resultado["COMPLEJIDAD_y"].value_counts())

resultado['COMPLEJIDAD'] = np.where(
    resultado['COMPLEJIDAD_y'].isna() | (resultado['COMPLEJIDAD_y'] == 'Unknown'), 
    resultado['COMPLEJIDAD_x'], 
    resultado['COMPLEJIDAD_y']
)

COMPLEJIDAD_x
LOW     191406
HIGH     18585
Name: count, dtype: int64
COMPLEJIDAD_y
LOW        230069
UNKNOWN     72445
HIGH        22971
Name: count, dtype: int64

In [245]:
resultado["COMPLEJIDAD"] = resultado["COMPLEJIDAD"].replace("UNKNOWN", np.nan)
print(resultado["COMPLEJIDAD"].value_counts())
print()
print(resultado["COMPLEJIDAD"].unique())

COMPLEJIDAD
LOW     230098
HIGH     22975
Name: count, dtype: int64

<ArrowStringArray>
[nan, 'LOW', 'HIGH']
Length: 3, dtype: str

In [246]:
resultado = resultado.drop(["COMPLEJIDAD_y", "COMPLEJIDAD_x"], axis=1)

In [255]:
# Identificar columnas mismo encabezado
columnas = [col for col in resultado.columns if "_x" in col or "_y" in col]
print(columnas)

[]

#### Unificacion KEV

In [282]:
print(resultado["HAS_KEV"].value_counts())
print(resultado["IS_KEV"].value_counts())

HAS_KEV
False    346166
True       1586
Name: count, dtype: int64
IS_KEV
0.0    323898
1.0      1587
Name: count, dtype: int64

In [284]:
resultado['KEV'] = np.where(
    resultado['IS_KEV'].isna(), 
    resultado['HAS_KEV'], 
    resultado['IS_KEV']
)

In [285]:
resultado["KEV"] = resultado["KEV"].replace("UNKNOWN", np.nan)
print(resultado["KEV"].value_counts())
print()
print(resultado["KEV"].unique())

KEV
0.0    346180
1.0      1587
Name: count, dtype: int64

[0.0 1.0]

In [286]:
resultado = resultado.drop(["IS_KEV", "HAS_KEV"], axis=1)

#### Unificaicon CWE

In [287]:
resultado.shape

(347767, 38)

In [288]:
resultado.columns

Index(['CVE_ID', 'PUBLISHED_DATE', 'MODIFIED_DATE', 'CVE_YEAR', 'DESC_EN',
       'ALCANCE', 'IMP_CONFID', 'IMP_INTEGR', 'IMP_DISPON', 'FACILIDAD',
       'CPE_VENDOR', 'CPE_PRODUCT', 'PATCH_URL', 'RISK_TIER', 'RISK_SCORE',
       'EPSS_SCORE', 'EPSS_PERCENTILE', 'DAYS_SINCE_PUBLISHED', 'VENDOR',
       'PRODUCT', 'VENDOR_TOKENS', 'PRODUCT_TOKENS', 'CWE_TOKENS',
       'VENDOR_GROUPS_STR', 'PRODUCT_GROUPS_STR', 'CWE_TECH_GROUPS_STR',
       'CWE_CANONICAL_STR', 'N_VENDOR_GROUPS', 'N_PRODUCT_GROUPS',
       'N_CWE_GROUPS', 'SEVERITY', 'SCORE_BASE', 'INTERACCION', 'PRIVILEGIOS',
       'VEC_ATAQUE', 'COMPLEJIDAD', 'ID_CWE', 'KEV'],
      dtype='str')

In [290]:
print(resultado["CWE_ID"].value_counts())
print(resultado["CWE"].value_counts())
print()
print()
print(resultado["CWE_ID"].unique())
print(resultado["CWE"].unique())
print()
print()
print(resultado["CWE_ID"].nunique())
print(resultado["CWE"].nunique())
print()
print()
print(resultado["CWE_ID"].isnull().sum())
print(resultado["CWE"].isnull().sum())

KeyError: 'CWE_ID'

In [291]:
conteo = (resultado['CWE_ID'] == resultado['CWE']).value_counts()
print(conteo)

KeyError: 'CWE_ID'

In [292]:
diferencias = resultado[resultado['CWE_ID'] != resultado['CWE']]
diferencias[["CWE_ID", "CWE"]].sample(40)

KeyError: 'CWE_ID'

In [293]:
resultado["ID_CWE"] = resultado["CWE_ID"] + ", " + resultado["CWE"]

KeyError: 'CWE_ID'

In [294]:
print(resultado["ID_CWE"].value_counts())
print()
print()
print(resultado["ID_CWE"].unique())
print()
print()
print(resultado["ID_CWE"].nunique())
print()
print()
print(resultado["ID_CWE"].isnull().sum())

ID_CWE
CWE-79, CWE-79               35353
CWE-89, CWE-89               13450
CWE-119, CWE-119             10791
CWE-20, CWE-20                7902
CWE-352, CWE-352              7503
                             ...
CWE-404, CWE-404, CWE-835        1
CWE-416, CWE-416, CWE-825        1
CWE-674, CWE-674, CWE-791        1
CWE-22, CWE-22, CWE-36           1
CWE-200, CWE-200, CWE-359        1
Name: count, Length: 7503, dtype: int64


<ArrowStringArray>
[                   'CWE-20, CWE-20',                  'CWE-119, CWE-119',
                                 nan,   'CWE-125, NVD-CWE-Other, CWE-125',
                  'CWE-327, CWE-327', 'CWE-1067, NVD-CWE-Other, CWE-1067',
   'CWE-290, NVD-CWE-Other, CWE-290',   'CWE-522, NVD-CWE-Other, CWE-522',
   'CWE-364, NVD-CWE-Other, CWE-364',   'CWE-434, NVD-CWE-Other, CWE-434',
 ...
         'CWE-404, CWE-404, CWE-407',           'CWE-20, CWE-20, CWE-943',
  'CWE-20, CWE-20, CWE-352, CWE-400',   'CWE-20, CWE-20, CWE-79, CWE-119',
         'CWE-459, CWE-459, CWE-668',         'CWE-404, CWE-404, CWE-835',
         'CWE-416, CWE-416, CWE-825',         'CWE-674, CWE-674, CWE-791',
            'CWE-22, CWE-22, CWE-36',         'CWE-200, CWE-200, CWE-359']
Length: 7504, dtype: str


7503


76515

In [295]:
resultado = resultado.drop(["CWE_ID", "CWE"], axis=1)

KeyError: "['CWE_ID', 'CWE'] not found in axis"

In [296]:
resultado.columns

Index(['CVE_ID', 'PUBLISHED_DATE', 'MODIFIED_DATE', 'CVE_YEAR', 'DESC_EN',
       'ALCANCE', 'IMP_CONFID', 'IMP_INTEGR', 'IMP_DISPON', 'FACILIDAD',
       'CPE_VENDOR', 'CPE_PRODUCT', 'PATCH_URL', 'RISK_TIER', 'RISK_SCORE',
       'EPSS_SCORE', 'EPSS_PERCENTILE', 'DAYS_SINCE_PUBLISHED', 'VENDOR',
       'PRODUCT', 'VENDOR_TOKENS', 'PRODUCT_TOKENS', 'CWE_TOKENS',
       'VENDOR_GROUPS_STR', 'PRODUCT_GROUPS_STR', 'CWE_TECH_GROUPS_STR',
       'CWE_CANONICAL_STR', 'N_VENDOR_GROUPS', 'N_PRODUCT_GROUPS',
       'N_CWE_GROUPS', 'SEVERITY', 'SCORE_BASE', 'INTERACCION', 'PRIVILEGIOS',
       'VEC_ATAQUE', 'COMPLEJIDAD', 'ID_CWE', 'KEV'],
      dtype='str')

In [297]:
resultado.shape

(347767, 38)

In [305]:
ajustadas = ["SEVERITY","SCORE_BASE","INTERACCION","PRIVILEGIOS","VEC_ATAQUE","COMPLEJIDAD","ID_CWE","KEV"]
columnas_restantes = [col for col in resultado.columns if col not in ajustadas]
print(resultado[columnas_restantes].sample(10))

                CVE_ID                   PUBLISHED_DATE  \
114157  CVE-2018-12871 2018-10-12 18:29:13.243000+00:00
19715    CVE-2006-3955        2006-08-01 21:04:00+00:00
307635  CVE-2025-37998 2025-05-29 14:15:36.450000+00:00
219171  CVE-2023-20017 2023-08-16 22:15:10.353000+00:00
297869  CVE-2025-23742 2025-02-14 13:15:46.033000+00:00
166220   CVE-2020-9801 2020-06-09 17:15:12.097000+00:00
208659  CVE-2022-40319 2023-01-17 21:15:13.320000+00:00
96933    CVE-2017-1290 2017-11-01 21:29:00.420000+00:00
135801  CVE-2019-17454 2019-10-10 17:15:17.907000+00:00
14980    CVE-2005-4064        2005-12-07 11:03:00+00:00

                          MODIFIED_DATE  CVE_YEAR  \
114157 2024-11-21 03:46:00.683000+00:00      2018
19715  2026-04-16 00:27:16.627000+00:00      2006
307635 2025-12-16 20:21:07.270000+00:00      2025
219171 2024-11-21 07:40:21.120000+00:00      2023
297869 2026-04-23 15:24:24.560000+00:00      2025
166220 2024-11-21 05:41:18.557000+00:00      2020
208659 2025-04-04 20:15:16.227000+00:00      2022
96933  2025-04-20 01:37:25.860000+00:00      2017
135801 2024-11-21 04:32:21.253000+00:00      2019
14980  2026-04-16 00:27:16.627000+00:00      2005

                                                  DESC_EN    ALCANCE  \
114157  Adobe Acrobat and Reader versions 2018.011.200...        NaN
19715   Multiple PHP remote file inclusion vulnerabili...        NaN
307635  In the Linux kernel, the following vulnerabili...  UNCHANGED
219171  Multiple vulnerabilities in Cisco Intersight P...  UNCHANGED
297869  Improper Neutralization of Input During Web Pa...    CHANGED
166220  A logic issue was addressed with improved rest...  UNCHANGED
208659  The LISTSERV 17 web interface allows remote at...  UNCHANGED
96933   IBM OpenPages GRC Platform 7.1, 7.2, and 7.3 i...        NaN
135801  Bento4 1.5.1.0 has a NULL pointer dereference ...  UNCHANGED
14980   Multiple SQL injection vulnerabilities in A-FA...        NaN

       IMP_CONFID IMP_INTEGR IMP_DISPON  FACILIDAD  ...  \
114157        NaN        NaN        NaN        NaN  ...
19715         NaN        NaN        NaN        NaN  ...
307635       NONE       NONE       HIGH        1.8  ...
219171       HIGH       HIGH       NONE        1.2  ...
297869        LOW        LOW        LOW        2.8  ...
166220        LOW        LOW        LOW        1.8  ...
208659       NONE       HIGH       NONE        3.9  ...
96933         NaN        NaN        NaN        NaN  ...
135801       NONE       NONE       HIGH        2.8  ...
14980         NaN        NaN        NaN        NaN  ...

                    VENDOR_TOKENS  \
114157  [microsoft, adobe, apple]
19715                    [minibb]
307635            [debian, linux]
219171                    [cisco]
297869                  [UNKNOWN]
166220                    [apple]
208659                    [lsoft]
96933                       [ibm]
135801                  [axiosys]
14980                 [alan_ward]

                                           PRODUCT_TOKENS        CWE_TOKENS  \
114157  [acrobat_reader_dc, mac_os_x, acrobat_dc, wind...         [cwe-125]
19715                                            [minibb]   [nvd-cwe-other]
307635                       [debian_linux, linux_kernel]  [nvd-cwe-noinfo]
219171             [intersight_private_virtual_appliance]  [cwe-78, cwe-77]
297869                                          [UNKNOWN]          [cwe-79]
166220                                           [safari]  [nvd-cwe-noinfo]
208659                                         [listserv]         [cwe-639]
96933                            [openpages_grc_platform]          [cwe-79]
135801                                           [bento4]         [cwe-476]
14980                                             [a-faq]   [nvd-cwe-other]

                VENDOR_GROUPS_STR  \
114157  microsoft | adobe | apple
19715                OTHER_VENDOR
307635             debian | linux
219171                      cisco
297869                    unknown
166220                      apple
208659               OTHER_VENDOR
96933                         ibm
135801               OTHER_VENDOR
14980                OTHER_VENDOR

                                       PRODUCT_GROUPS_STR  \
114157  office_suite | apple_ecosystem | windows_ecosy...
19715                                      other_software
307635                                    linux_ecosystem
219171                                     other_software
297869                                     other_software
166220                                            browser
208659                                     other_software
96933                                      other_software
135801                                     other_software
14980                                      other_software

        CWE_TECH_GROUPS_STR  CWE_CANONICAL_STR  N_VENDOR_GROUPS  \
114157    memory_corruption            cwe-787              3.0
19715                 other      nvd-cwe-other              1.0
307635              unknown     nvd-cwe-noinfo              2.0
219171    command_injection             cwe-78              1.0
297869        xss_injection             cwe-79              1.0
166220              unknown     nvd-cwe-noinfo              1.0
208659                other            cwe-639              1.0
96933         xss_injection             cwe-79              1.0
135801         null_pointer            cwe-476              1.0
14980                 other      nvd-cwe-other              1.0

       N_PRODUCT_GROUPS N_CWE_GROUPS
114157              3.0          1.0
19715               1.0          1.0
307635              1.0          1.0
219171              1.0          1.0
297869              1.0          1.0
166220              1.0          1.0
208659              1.0          1.0
96933               1.0          1.0
135801              1.0          1.0
14980               1.0          1.0

[10 rows x 30 columns]

AttributeError: 'list' object has no attribute 'sample'

In [298]:
resultado.head(10)

,CVE_ID,PUBLISHED_DATE,MODIFIED_DATE,CVE_YEAR,DESC_EN,ALCANCE,IMP_CONFID,IMP_INTEGR,IMP_DISPON,FACILIDAD,...,N_PRODUCT_GROUPS,N_CWE_GROUPS,SEVERITY,SCORE_BASE,INTERACCION,PRIVILEGIOS,VEC_ATAQUE,COMPLEJIDAD,ID_CWE,KEV
0,CVE-1999-0001,1999-12-30 05:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,ip_input.c in BSD-derived TCP/IP implementatio...,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,5.0,NaN,NaN,NaN,NaN,"CWE-20, CWE-20",0.0
1,CVE-1999-0002,1998-10-12 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,Buffer overflow in NFS mountd gives root acces...,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,NaN,10.0,NaN,NaN,NaN,NaN,"CWE-119, CWE-119",0.0
2,CVE-1999-0003,1998-04-01 05:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,Execute commands as root via buffer overflow i...,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,NaN,10.0,NaN,NaN,NaN,NaN,NaN,0.0
3,CVE-1999-0004,1997-12-16 05:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,"MIME buffer overflow in email clients, e.g. So...",NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,0.0
4,CVE-1999-0005,1998-07-20 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,Arbitrary command execution via IMAP buffer ov...,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,10.0,NaN,NaN,NaN,NaN,NaN,0.0
5,CVE-1999-0006,1998-07-14 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,Buffer overflow in POP servers based on BSD/Qu...,UNCHANGED,HIGH,HIGH,HIGH,3.9,...,1.0,2.0,CRITICAL,9.8,NONE,NONE,NETWORK,LOW,"CWE-125, NVD-CWE-Other, CWE-125",0.0
6,CVE-1999-0007,1998-06-26 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,Information from SSL-encrypted sessions via PK...,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,NaN,5.0,NaN,NaN,NaN,NaN,"CWE-327, CWE-327",0.0
7,CVE-1999-0008,1998-06-08 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,"Buffer overflow in NIS+, in Sun's rpc.nisd pro...",NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,NaN,10.0,NaN,NaN,NaN,NaN,NaN,0.0
8,CVE-1999-0009,1998-04-08 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,Inverse query buffer overflow in BIND 4.9 and ...,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,NaN,10.0,NaN,NaN,NaN,NaN,NaN,0.0
9,CVE-1999-0010,1998-04-08 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,Denial of Service vulnerability in BIND 8 Rele...,NaN,NaN,NaN,NaN,NaN,...,2.0,1.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,0.0

In [107]:
resultado["SEVERITY_y"] = resultado["SEVERITY_y"].replace("UNKNOWN", np.nan)
select = resultado.loc[resultado["SON_IGUALES"] == False, ["CVE_ID", "SEVERITY_x", "SEVERITY_y"]]
#select
select.sample(30)

                CVE_ID SEVERITY_x SEVERITY_y
70197    CVE-2014-6120        NaN   CRITICAL
36424    CVE-2008-7037        NaN        NaN
185557  CVE-2021-42248        NaN        NaN
121605   CVE-2018-2419        NaN        LOW
327284  CVE-2025-68317        NaN        NaN
11181    CVE-2005-0168        NaN        NaN
37426    CVE-2009-0743        NaN        NaN
125717   CVE-2018-7031        NaN        NaN
133202  CVE-2019-14617        NaN        NaN
49215    CVE-2011-2405        NaN        NaN
26419    CVE-2007-3522        NaN        NaN
60567    CVE-2013-2874        NaN        NaN
16940    CVE-2006-1148        NaN        NaN
87423    CVE-2016-3856        NaN       HIGH
91031    CVE-2016-7815        NaN     MEDIUM
124086   CVE-2018-4986        NaN       HIGH
100735  CVE-2017-17108        NaN   CRITICAL
101458  CVE-2017-17866        NaN       HIGH
107258   CVE-2017-6808        NaN     MEDIUM
134090  CVE-2019-15534        NaN   CRITICAL
30219    CVE-2008-0717        NaN        NaN
114270  CVE-2018-13013        NaN       HIGH
55360    CVE-2012-3760        NaN        NaN
3922     CVE-2001-1135        NaN        NaN
54701    CVE-2012-3036        NaN        NaN
26973    CVE-2007-4090        NaN        NaN
28106    CVE-2007-5274        NaN        NaN
98262   CVE-2017-14538        NaN       HIGH
50897    CVE-2011-4215        NaN        NaN
2887     CVE-2001-0066        NaN        NaN

In [108]:
conteo = (resultado['SEVERITY_x'] == resultado['SEVERITY_y']).value_counts()
print(conteo)

True     209958
False    137809
Name: count, dtype: int64

In [46]:
diferencias = resultado[resultado['SEVERITY_x'] != resultado['SEVERITY_y']]
diferencias.sample(20)

,CVE_ID,PUBLISHED_DATE,MODIFIED_DATE,CVE_YEAR,HAS_KEV,DESC_EN,SCORE_BASE_x,SEVERITY_x,VEC_ATAQUE_x,COMPLEJIDAD_x,...,VENDOR_TOKENS,PRODUCT_TOKENS,CWE_TOKENS,VENDOR_GROUPS_STR,PRODUCT_GROUPS_STR,CWE_TECH_GROUPS_STR,CWE_CANONICAL_STR,N_VENDOR_GROUPS,N_PRODUCT_GROUPS,N_CWE_GROUPS
74059,CVE-2015-0395,2015-01-21 18:59:38.903000+00:00,2025-04-12 10:46:40.837000+00:00,2015,False,Unspecified vulnerability in Oracle Java SE 5....,NaN,NaN,NaN,NaN,...,"[opensuse, redhat, debian, oracle, novell, can...","[jre, debian_linux, opensuse, jdk, suse_linux_...",[nvd-cwe-noinfo],opensuse | redhat | debian | oracle | novell |...,developer_runtime | linux_ecosystem,unknown,nvd-cwe-noinfo,6.0,2.0,1.0
11118,CVE-2005-0100,2005-02-07 05:00:00+00:00,2026-04-16 00:27:16.627000+00:00,2005,False,Format string vulnerability in the movemail ut...,NaN,NaN,NaN,NaN,...,[gnu],"[emacs, xemacs]",[nvd-cwe-other],gnu,other_software,other,nvd-cwe-other,1.0,1.0,1.0
56823,CVE-2012-5502,2014-09-30 14:55:06.673000+00:00,2025-04-12 10:46:40.837000+00:00,2012,False,Cross-site scripting (XSS) vulnerability in sa...,NaN,NaN,NaN,NaN,...,[plone],[plone],[cwe-79],OTHER_VENDOR,other_software,xss_injection,cwe-79,1.0,1.0,1.0
68545,CVE-2014-4232,2014-07-17 05:10:16.780000+00:00,2025-04-12 10:46:40.837000+00:00,2014,False,Unspecified vulnerability in the Oracle Secure...,NaN,NaN,NaN,NaN,...,[oracle],"[virtualization_secure_global_desktop, virtual...",[nvd-cwe-noinfo],oracle,other_software,unknown,nvd-cwe-noinfo,1.0,1.0,1.0
142029,CVE-2019-5727,2019-02-21 01:29:00.227000+00:00,2024-11-21 04:45:24.270000+00:00,2019,False,Splunk Web in Splunk Enterprise 6.5.x before 6...,NaN,NaN,NaN,NaN,...,[splunk],[splunk],[cwe-79],OTHER_VENDOR,other_software,xss_injection,cwe-79,1.0,1.0,1.0
9617,CVE-2004-1364,2004-08-04 04:00:00+00:00,2026-04-16 00:27:16.627000+00:00,2004,False,Directory traversal vulnerability in extproc i...,NaN,NaN,NaN,NaN,...,[oracle],"[enterprise_manager, application_server, e-bus...",[cwe-22],oracle,other_software | enterprise_app,path_traversal,cwe-22,1.0,2.0,1.0
101737,CVE-2017-18171,2018-10-23 13:29:00.417000+00:00,2024-11-21 03:19:28.703000+00:00,2017,False,Improper input validation for GATT data packet...,NaN,NaN,NaN,NaN,...,[qualcomm],"[sd_450_firmware, sd_625, sd_845_firmware, sdm...",[cwe-119],qualcomm,firmware_iot | other_software,memory_corruption,cwe-787,1.0,2.0,1.0
61415,CVE-2013-3822,2013-07-17 13:41:16.977000+00:00,2026-04-29 01:13:23.040000+00:00,2013,False,Unspecified vulnerability in the Oracle Agile ...,NaN,NaN,NaN,NaN,...,[oracle],[supply_chain_products_suite],[nvd-cwe-noinfo],oracle,other_software,unknown,nvd-cwe-noinfo,1.0,1.0,1.0
81838,CVE-2015-8929,2016-09-20 14:15:16.087000+00:00,2025-04-12 10:46:40.837000+00:00,2015,False,Memory leak in the __archive_read_get_extract ...,NaN,NaN,NaN,NaN,...,"[suse, libarchive]","[linux_enterprise_desktop, linux_enterprise_se...",[cwe-119],suse | OTHER_VENDOR,linux_ecosystem | other_software,memory_corruption,cwe-787,2.0,2.0,1.0
1342,CVE-1999-1362,1999-12-31 05:00:00+00:00,2026-04-16 00:27:16.627000+00:00,1999,False,Win32k.sys in Windows NT 4.0 before SP2 allows...,NaN,NaN,NaN,NaN,...,[microsoft],[windows_nt],[nvd-cwe-other],microsoft,windows_ecosystem,other,nvd-cwe-other,1.0,1.0,1.0
337263,CVE-2026-25701,2026-02-25 12:16:17.763000+00:00,2026-04-15 00:35:42.020000+00:00,2026,False,An Insecure Temporary File vulnerability in op...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42727,CVE-2010-0993,2010-04-09 17:30:00.350000+00:00,2026-04-29 01:13:23.040000+00:00,2010,False,Unrestricted file upload vulnerability in Puls...,NaN,NaN,NaN,NaN,...,[pulsecms],[pulse_cms],[nvd-cwe-other],OTHER_VENDOR,other_software,other,nvd-cwe-other,1.0,1.0,1.0
68278,CVE-2014-3932,2014-06-02 14:55:03.327000+00:00,2025-04-12 10:46:40.837000+00:00,2014,False,SQL injection vulnerability in the device regi...,NaN,NaN,NaN,NaN,...,[cososys],[endpoint_protector],[cwe-89],OTHER_VENDOR,other_software,database_injection,cwe-89,1.0,1.0,1.0
94546,CVE-2017-10104,2017-08-08 15:29:03.397000+00:00,2025-04-20 01:37:25.860000+00:00,2017,False,Vulnerability in the Java Advanced Management ...,NaN,NaN,NaN,NaN,...,[oracle],[java_advanced_management_console],[cwe-269],oracle,other_software,privilege_management,cwe-269,1.0,1.0,1.0
89375,CVE-2016-5970,2016-09-26 04:59:24.497000+00:00,2025-04-12 10:46:40.837000+00:00,2016,False,Directory traversal vulnerability in IBM Secur...,NaN,NaN,NaN,NaN,...,[ibm],[security_privileged_identity_manager_virtual_...,"[cwe-22, cwe-200]",ibm,other_software,path_traversal | information_disclosure,cwe-22 | cwe-200,1.0,1.0,2.0
246434,CVE-2023-54144,2025-12-24 13:16:16.413000+00:00,2026-04-15 00:35:42.020000+00:00,2023,False,"In the Linux kernel, the following vulnerabili...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72019,CVE-2014-8067,2017-05-11 14:29:40.390000+00:00,2023-11-07 02:22:14.193000+00:00,2014,False,Rejected reason: DO NOT USE THIS CANDIDATE NUM...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104759,CVE-2017-4025,2018-03-16 14:29:03.517000+00:00,2023-11-07 02:44:45.810000+00:00,2017,False,Rejected reason: DO NOT USE THIS CANDIDATE NUM...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46534,CVE-2010-4865,2011-10-05 10:55:07.893000+00:00,2026-04-29 01:13:23.040000+00:00,2010,False,SQL injection vulnerability in the JE Guestboo...,NaN,NaN,NaN,NaN,...,"[joomla, harmistechnology]","[com_jeguestbook, joomla\!]",[cwe-89],joomla | OTHER_VENDOR,other_software | cms,database_injection,cwe-89,2.0,2.0,1.0
106531,CVE-2017-5934,2018-10-15 19:29:00.507000+00:00,2024-11-21 03:28:42.110000+00:00,2017,False,Cross-site scripting (XSS) vulnerability in th...,NaN,NaN,NaN,NaN,...,"[debian, canonical, moinmo, opensuse]","[leap, moinmoin, ubuntu_linux, debian_linux]",[cwe-79],debian | canonical | OTHER_VENDOR | opensuse,linux_ecosystem | other_software,xss_injection,cwe-79,4.0,2.0,1.0

In [ ]:
select = resultado[["CVE_ID", "SEVERITY_x", "SEVERITY_y"]]
select.sample(20)

In [36]:
select = resultado.loc[resultado["N_VENDOR_GROUPS"] > 1, ["CVE_ID", "VENDOR", "CPE_VENDOR"]]
#select
select.sample(30)

,CVE_ID,VENDOR,CPE_VENDOR
147393,CVE-2020-11087,"freerdp, opensuse, debian",freerdp
163518,CVE-2020-6574,"apple, opensuse, debian, google, fedoraproject",google
114029,CVE-2018-12755,"microsoft, adobe, apple",adobe
49294,CVE-2011-2487,"redhat, apache",apache
118399,CVE-2018-17953,"kernel, opensuse, suse",kernel
49834,CVE-2011-3067,"google, apple",google
124675,CVE-2018-5712,"php, canonical, debian",php
138021,CVE-2019-20388,"xmlsoft, opensuse, debian, fedoraproject, orac...",xmlsoft
131284,CVE-2019-12466,"mediawiki, debian",mediawiki
183155,CVE-2021-39226,"grafana, fedoraproject",grafana
103708,CVE-2017-2887,"libsdl, debian",libsdl
132310,CVE-2019-13574,"debian, minimagick_project",minimagick_project
77085,CVE-2015-3643,"canonical, usb-creator_project",usb-creator_project
145236,CVE-2019-9798,"google, mozilla",mozilla
142103,CVE-2019-5818,"debian, opensuse, google, fedoraproject",google
237476,CVE-2023-42652,"unisoc, google",google
91874,CVE-2016-8683,"graphicsmagick, opensuse, debian",graphicsmagick
9333,CVE-2004-1068,"ubuntu, redhat, linux",linux
297248,CVE-2025-23158,"debian, linux",linux
180682,CVE-2021-3603,"phpmailer_project, fedoraproject",phpmailer_project
59316,CVE-2013-1500,"sun, oracle",oracle
53423,CVE-2012-1633,"drupal, erikwebb",erikwebb
200689,CVE-2022-30292,"squirrel-lang, fedoraproject",squirrel-lang
112451,CVE-2018-11040,"vmware, oracle, debian",vmware
193694,CVE-2022-2207,"vim, fedoraproject",vim
132050,CVE-2019-13297,"opensuse, canonical, debian, imagemagick",imagemagick
168530,CVE-2021-20354,"ibm, oracle, linux, microsoft, hp",ibm
177750,CVE-2021-3197,"debian, saltstack, fedoraproject",saltstack
102288,CVE-2017-18694,"samsung, google",google
183223,CVE-2021-3930,"redhat, debian, qemu",qemu

In [17]:
select = resultado[["CVE_ID", "SEVERITY_x", "SEVERITY_y"]]
select.sample(20)

                CVE_ID SEVERITY_x SEVERITY_y
302727  CVE-2025-30468     MEDIUM     MEDIUM
164850   CVE-2020-8188       HIGH       HIGH
32911    CVE-2008-3464        NaN    UNKNOWN
35352    CVE-2008-5965        NaN    UNKNOWN
261068  CVE-2024-28786     MEDIUM     MEDIUM
108070   CVE-2017-7731        NaN       HIGH
220245  CVE-2023-21284     MEDIUM     MEDIUM
344141  CVE-2026-39345     MEDIUM     MEDIUM
157953  CVE-2020-28044     MEDIUM     MEDIUM
143788   CVE-2019-8115     MEDIUM     MEDIUM
189886   CVE-2022-0175     MEDIUM     MEDIUM
327284  CVE-2025-68317        NaN        NaN
9334     CVE-2004-1069        NaN    UNKNOWN
321498  CVE-2025-59416        NaN        NaN
73010    CVE-2014-9268        NaN    UNKNOWN
6404     CVE-2002-2080        NaN    UNKNOWN
141496   CVE-2019-5163       HIGH       HIGH
112968  CVE-2018-11578        NaN     MEDIUM
12744    CVE-2005-1765        NaN    UNKNOWN
329828   CVE-2025-8062     MEDIUM     MEDIUM

In [18]:
columnas = [col for col in resultado.columns if "_x" in col or "_y" in col]
print(columnas)

['SCORE_BASE_x', 'SEVERITY_x', 'VEC_ATAQUE_x', 'COMPLEJIDAD_x', 'PRIVILEGIOS_x', 'INTERACCION_x', 'SCORE_BASE_y', 'SEVERITY_y', 'VEC_ATAQUE_y', 'COMPLEJIDAD_y', 'PRIVILEGIOS_y', 'INTERACCION_y']

In [23]:
select = resultado[["CVE_ID", "HAS_KEV", "IS_KEV"]]
select.sample(20)
select.nunique()

CVE_ID     347767
HAS_KEV         2
IS_KEV          2
dtype: int64